### PR TITLE
Pull request for #51

### PR DESCRIPTION
**Pull request by amihaiemil**
This PR is for issue #51 . I added maven-enforcer-plugin to pom.xml, to solve the issue. 
Also, I fixed site.xml because qulice validator was complaining (I copy pasted what Qulice said it should have contained, I hope it's OK).

### CODE REVIEW

**Comment by dmarkov** [comment]
@amihaiemil Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@longtimeago could you please review this pull request

**Comment by longtimeago** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@yegor256 Please let rultor merge if everything is ok, so we can close the ticket. Thanks.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by longtimeago** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by longtimeago** [comment]
@yegor256 please, help us with this case

**Comment by dmarkov** [comment]
@longtimeago I added **18 mins** to your account, many thanks for working with the project (77675480)! The completion time here was 120 hours and 10 mins.

extra minutes for review comments (c=3)

+18 added to your rating, at the moment it is: [+4648](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
