### PR TITLE
Add index.html to site for aggregation

### PR DESCRIPTION
**Pull request by psaladna**
Update to add  <report>index</report> to the list of reports to support aggregation of the site. See https://issues.apache.org/jira/browse/MSITE-425 for more information.

### CODE REVIEW

**Comment by dmarkov** [comment]
@psaladna I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@psaladna thanks!

**Comment by dmarkov** [comment]
@yegor256 **17 mins** added to your account (payment number `000-59e158b9`), many thanks for your contribution! 72 hours and 22 mins spent here.

extra minutes for review comments (c=2)

+17 to your rating, your total score is [+4770](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
