### PR TITLE
#76 Fixed error to execute xcop in Windows OS

### PR DESCRIPTION
**Pull request by fabriciofx**
Fixes issue #76. Tested on Windows 10 *and* Ubuntu 18.10.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#85](https://github.com/jcabi/jcabi-parent/issues/85) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#85](https://github.com/jcabi/jcabi-parent/issues/85); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by salgadobreno** [comment]
Tested on a macOS, no errors.

**Comment by fabriciofx** [comment]
@yegor256 WDYT? Is it ok to merge?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#85](https://github.com/jcabi/jcabi-parent/issues/85); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by fabriciofx** [comment]
@yegor256 ping

**Comment by fabriciofx** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#85` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#85](https://github.com/jcabi/jcabi-parent/issues/85) is now out of scope

**Comment by fabriciofx** [comment]
@yegor256 Can you release a new version?

**Comment by fabriciofx** [comment]
@yegor256 Sorry, I've seen released it now.

**Pull request merged**
