### PR TITLE
Updating jcabi-github version to 0.22 (latest release)

### PR DESCRIPTION
**Pull request by super132**
For task #25 , updating POM.xml to refer to `jcabi-github` 0.22.

### CODE REVIEW

**Comment by super132** [comment]
@dmarkov , please review this PR. Thanks.

**Comment by dmarkov** [comment]
@super132 Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@ggajos this pull request is for you, please review

**Comment by dmarkov** [comment]
> @dmarkov , please review this PR. Thanks.

@super132 thanks, will take a look

**Comment by ggajos** [comment]
@yegor256 should I reject this PR?

**Comment by super132** [comment]
@ggajos , may I know why this PR should be rejected? Did I do something wrong? Thanks.

**Comment by ggajos** [comment]
@dmarkov @super132 @yegor256 according to rules, 3 CR issues have to be found, otherwise the PR is too small and should be rejected. @yegor256 am I correct?

**Comment by super132** [comment]
@ggajos understood but this is the only required change. If this PR is rejected then I do not know how to produce a PR with more complicated changes. @yegor256 would you please advise on this? Thanks.

**Comment by yegor256** [comment]
@ggajos you're right, there is nothing to review here. I will just merge it, but code review here is not required.

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
