### PR TITLE
Qulice maven plugin added with default configuration to PluginManagement - Issue #19

### PR DESCRIPTION
**Pull request by Marczeeee**
Issue #19

### CODE REVIEW

**Comment by dmarkov** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@longtimeago please review this PR

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by maurezen** [comment]
@longtimeago @rultor will release be done?

**Comment by longtimeago** [comment]
@yegor256 please, make a release

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.1`

**Comment by dmarkov** [comment]
@longtimeago Thanks a lot, I just topped your account for **17 mins**, transaction ID `50593346`; +17 to your rating, your total score is [+1297](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
