### PR TITLE
Replace gmaven-plugin with gmavenplus-plugin

### LINKED ISSUE #29: gmaven-plugin has been discontinued
gmaven-plugin has been discontinued and there is a dependency incompatibility between groovy-all 2.3.3 and gmaven-plugin that uses groovy 2.0 (see providerSelection = 2.0). 
It leads to errors with Spock Framework.
gmaven-plugin should be replaced by gmavenplus-plugin.

```
				<plugin>
					<groupId>org.codehaus.gmavenplus</groupId>
					<artifactId>gmavenplus-plugin</artifactId>
					<version>1.5</version>
				</plugin>
```

### PR DESCRIPTION
**Pull request by Suseika**
Fixes #29

### CODE REVIEW

**Comment by Suseika** [comment]
@dmarkov Please find a reviewer for this PR

**Comment by dmarkov** [comment]
@suseika Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@yegor256 I just added **16 mins** to your account, many thanks for your contribution (000-f0d2a49c).. 22 hours and 13 mins spent here

you're getting extra minutes here (c=1)

+16 added to your rating, at the moment it is: [+5875](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
