### PR TITLE
added jakarta namespace

### PR DESCRIPTION
**Pull request by PeJetuz**
@yegor256 
Hi!
Is it ok? I want to add the jakarta namespace in takes [1307](https://github.com/yegor256/takes/issues/1307)
Or these dependencies should be in takes only?

### CODE REVIEW

**Comment by yegor256** [comment]
@PeJetuz thanks for your contribution! It's good to have these deps in jcabi-parent. However, we can't merge now because some CI actions are not passing. Please, fix them.

**Comment by PeJetuz** [comment]
@yegor256 fixed. Thanks!

**Comment by yegor256** [comment]
@PeJetuz not really :(

**Comment by PeJetuz** [comment]
I'm sorry, can I check the build without disturbing you?

**Comment by yegor256** [comment]
@PeJetuz see the output of XCOP. Empty lines are prohibited in XML.

**Comment by PeJetuz** [comment]
@yegor256 
Thank you! I installed Ruby with XCOP and fixed the pom.xml.
I found a red '\n' in the output, it was hard to see in the large output :(
I hope the checks are now successful.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.68.0`

**Comment by yegor256** [comment]
@PeJetuz thanks a lot, new version (0.68.0) released to Maven Central

**Comment by PeJetuz** [comment]
@yegor256 Thank you very much!
Please review if possible [1309](https://github.com/yegor256/takes/pull/1309).

**Pull request merged**
