### PR TITLE
Increased nexus staging timeout

### PR DESCRIPTION
**Pull request by g4s8**
#98 - changed Nexus staging plugin timeout from default 5 minutes to 10 minutes.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor release, tag is `0.50.1`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#99` is not assigned, can't get performer

**Pull request merged**
