### PR TITLE
prevent Maven 3.5 build warnings related to reporting

### PR DESCRIPTION
**Pull request by dejan2609**
(plugin definitions are moved from 'maven-site-plugin/reportPlugins' section into newly created 'reporting' section)

`Solves issue: `#69 **_(warning about maven-site-plugin)_**

`Related links:`
- https://issues.apache.org/jira/browse/MNG-6189 **_WARN if maven-site-plugin configuration contains reportPlugins element_**
- https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Configuring_Reporting_Plugins

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.48.6`

**Comment by yegor256** [comment]
@dejan2609 thanks!

**Comment by dejan2609** [comment]
You're welcome @yegor256 ! 
Regards.

**Comment by dejan2609** [comment]
Note: this PR closes #71

**Pull request merged**
