### PR TITLE
#57 Adding jacoco as a default coverage control tool instead of cobertura

### PR DESCRIPTION
**Pull request by longtimeago**
#57 Adding jacoco as a default coverage control tool instead of cobertura

### CODE REVIEW

**Comment by longtimeago** [comment]
@dmarkov please, find a reviewer

**Comment by dmarkov** [comment]
@longtimeago Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@hdouss please review this PR

**Comment by HDouss** [comment]
@longtimeago I am not sure but shouldn't we add jacoco plugin in the site profile ?

**Comment by HDouss** [comment]
@longtimeago Aren't the rules too strict ? We generally tend to write small classes, at least whenever possible. Small classes are very hard to cover at 0.8 rate, especially when using syntaxic sugar features as : try-with-resource or lombok.

**Comment by longtimeago** [comment]
@HDouss I'm also not sure about site profile
For the `0.8` it's the default target coverage for opensource projects. In any case, each project could/will customize these rates

**Comment by HDouss** [comment]
@longtimeago I suggest to add it to site profile:
* This was the case for cobertura
* This is the way done in other teamed.io projects that rely on jacoco

**Comment by dmarkov** [comment]
> @dmarkov please, find a reviewer

@longtimeago OK

**Comment by longtimeago** [comment]
@HDouss sorry, I'm on vacation starting from today, can't finish the issue in time :(

**Comment by dmarkov** [comment]
@hdouss Much obliged! I have added **18 mins** to your account in payment "91476685", 72 hours and 32 mins spent... extra minutes for review comments (c=3)... +18 added to your rating, at the moment it is: [+1085](http://www.netbout.com/b/36032?open=rating)

**Pull request closed without merging**
