### PR TITLE
Updated unit testing dependencies

### PR DESCRIPTION
**Pull request by g4s8**
Updated junit to `5.4.2` version, updated hamcrest to `2.1` version

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.9`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#93` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.9`

**Comment by yegor256** [comment]
@g4s8 released

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
