### PR TITLE
Upgrade jcabi-maven-plugin to 0.13

### PR DESCRIPTION
**Pull request by cvrebert**
Refs https://github.com/jcabi/jcabi-maven-plugin/pull/35

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by cvrebert** [comment]
@yegor256 Tag a new release please.

**Comment by yegor256** [comment]
@rultor release, tag is `0.34`

**Comment by cvrebert** [comment]
@yegor256 Thanks. Next is https://github.com/jcabi/jcabi/pull/304

**Pull request merged**
