### PR TITLE
#57 Adding jacoco to pluginManagement section

### PR DESCRIPTION
**Pull request by prondzyn**
This is for #57.

I added jacoco to pluginManagement section to be inherited by children poms.

### CODE REVIEW

**Comment by dmarkov** [comment]
@prondzyn Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by prondzyn** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 Much appreciated! **16 mins** was added to your account, payment ID `000-73806721`, time spent is 118 hours and 19 mins; extra minutes for review comments (c=1); +16 added to your rating, current score is: [+268](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
