### PR TITLE
maven-compiler-plugin to 3.7.0

### PR DESCRIPTION
**Pull request by candrews**
http://maven.40175.n5.nabble.com/ANN-Apache-Maven-Compiler-Plugin-3-7-0-Released-td5913615.html

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#77](https://github.com/jcabi/jcabi-parent/issues/77) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor release, tag is `0.49.3`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-parent#77` is not assigned, can't get start time

**Comment by yegor256** [comment]
@candrews thanks, version 0.49.3 will hav eit.

**Comment by 0crat** [comment]
The job [#77](https://github.com/jcabi/jcabi-parent/issues/77) is now out of scope

**Comment by 0crat** [comment]
Job [#77](https://github.com/jcabi/jcabi-parent/issues/77) was not in scope

**Pull request merged**
