### PR TITLE
#17 - fixed copyright section

### PR DESCRIPTION
**Pull request by RomanKisilenko**
Please review this PR.

### CODE REVIEW

**Comment by dmarkov** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@carlosmiranda review this one please

**Comment by carlosmiranda** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@carlosmiranda **16 mins** added to your account (payment number `50570408`), many thanks for your contribution!. +16 to your rating, your total score is [+1730](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
